version: '3.3'

services:
  ner_service1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
  ner_service2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ner_service1
      - ner_service2
